spring.application.name=anti-fraud-service
server.port=8082

# Kafka (docker host listener)
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=anti-fraud-service
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.value.default.type=pe.indigital.yape.antifraud.adapters.in.messaging.kafka.dto.TransactionCreatedEvent
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.producer.properties.spring.json.add.type.headers=false

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

app.kafka.topics.transaction-created=transactions.created
app.kafka.topics.transaction-status-updated=transactions.status-updated
